# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
