# Generated by Django 1.9 on 2016-05-31 09:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                max_length=254,
                verbose_name="Email address",
            ),
        ),
    ]
