# Generated by Django 1.9 on 2016-06-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bags", "0008_auto_20160608_1212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Herr", "Herr"),
                    ("Frau", "Frau"),
                ],
                max_length=200,
                verbose_name="Contact person (Gender)",
            ),
        ),
    ]
