# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import settool_common.models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0011_auto_20160710_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='semester',
            field=models.ForeignKey(default=settool_common.models.current_semester, on_delete=django.db.models.deletion.CASCADE, to='settool_common.Semester'),
        ),
    ]
