# Generated by Django 1.10 on 2017-06-19 14:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bags", "0012_auto_20160924_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="giveaways_last_year",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Giveaways last year",
            ),
        ),
    ]
