# Generated by Django 2.0.4 on 2018-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0013_company_giveaways_last_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='semester',
            field=models.ForeignKey(on_delete=None, to='settool_common.Semester'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='semester',
            field=models.ForeignKey(on_delete=None, to='settool_common.Semester'),
        ),
    ]
