# Generated by Django 2.0.4 on 2018-10-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bags", "0014_auto_20180704_0855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.Semester",
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.Semester",
            ),
        ),
    ]
