# Generated by Django 3.1.5 on 2021-01-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bags", "0016_auto_20201209_1909"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mail",
            name="semester",
        ),
    ]
