# Generated by Django 3.1.5 on 2021-01-30 20:03

import django.db.models.deletion
from django.db import migrations, models

import settool_common.models as common_models


def migrate_mail_bagmail(apps, _):
    Mail = apps.get_model("bags", "Mail")
    BagMail = apps.get_model("bags", "BagMail")
    for mail in Mail.objects.all():
        BagMail.objects.create(
            sender=common_models.Mail.SET_BAGS,
            subject=mail.subject,
            text=mail.text,
            comment=mail.comment,
        )
        mail.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
        ("bags", "0017_remove_mail_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="BagMail",
            fields=[
                (
                    "mail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="settool_common.mail",
                    ),
                ),
            ],
            bases=("settool_common.mail",),
        ),
        migrations.RunPython(migrate_mail_bagmail),
        migrations.DeleteModel(
            name="Mail",
        ),
    ]
