# Generated by Django 3.1.6 on 2021-02-17 21:30

from django.db import migrations


def rename_duplicates(apps, _):
    Company = apps.get_model("bags", "company")
    company: Company
    index = 0
    for company in Company.objects.all():
        if (
            Company.objects.filter(
                semester=company.semester,
                name=company.name,
            ).count()
            > 1
        ):
            company.name = f"{company.name}-{index}"
            company.save()
            index += 1


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
        ("bags", "0018_auto_20210130_2103"),
    ]

    operations = [
        migrations.RunPython(rename_duplicates),
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("semester", "name")},
        ),
    ]
