# Generated by Django 3.1.7 on 2021-03-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0015_auto_20210319_2055"),
        ("bags", "0020_auto_20210321_1611"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giveaway",
            name="every_x_bags",
        ),
        migrations.RemoveField(
            model_name="giveaway",
            name="per_bag_count",
        ),
        migrations.AddField(
            model_name="giveaway",
            name="item_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Amount of this Givaway"),
        ),
        migrations.CreateModel(
            name="BagSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bag_count", models.PositiveSmallIntegerField(default=0, verbose_name="Item Count")),
                (
                    "semester",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="settool_common.semester"),
                ),
            ],
        ),
    ]
