# Generated by Django 3.1.7 on 2021-03-30 09:54

import django.db.models.deletion
from django.db import migrations, models


def keep_giveaway_data(apps, _):
    Giveaway = apps.get_model("bags", "Giveaway")
    for giveaway in Giveaway.objects.all():
        giveaway.comment = giveaway.name
        giveaway.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bags", "0022_auto_20210326_2043"),
    ]

    operations = [
        migrations.AddField(
            model_name="giveaway",
            name="comment",
            field=models.CharField(blank=True, max_length=200, verbose_name="Giveaway-description/comment"),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bags.giveawaygroup",
                verbose_name="Giveaway-title/group/tag",
            ),
        ),
        migrations.RunPython(keep_giveaway_data),
        migrations.RemoveField(model_name="giveaway", name="name"),
    ]
