# Generated by Django 3.1.7 on 2021-03-30 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0015_auto_20210319_2055"),
        ("bags", "0023_auto_20210330_1154"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="giveawaygroup",
            unique_together={("semester", "name")},
        ),
    ]
