# Generated by Django 4.0.3 on 2022-04-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0018_alter_anonymisationlog_semester"),
        ("bags", "0026_bagsettings_created_at_bagsettings_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AlterField(
            model_name="giveawaygroup",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
    ]
