# Generated by Django 2.0.4 on 2018-08-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0007_auto_20180705_1345"),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="mail_declined_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors_mail_declined_place",
                to="settool_common.Mail",
                verbose_name="Mail Declined Place",
            ),
        ),
        migrations.AddField(
            model_name="subjecttutorcountassignment",
            name="waitlist",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subjecttutorcountassignment",
            name="wanted",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
            ),
        ),
    ]
