# Generated by Django 2.0.4 on 2018-10-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20180816_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='semester',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='settool_common.Semester'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('active', 'active'), ('declined', 'declined'), ('inactive', 'inactive'), ('employee', 'employee')], default='inactive', max_length=100, verbose_name='Status'),
        ),
    ]
