# Generated by Django 3.1.5 on 2021-01-30 20:03

import django.db.models.deletion
from django.db import migrations, models

import settool_common.models


def migrate_mail_tutormail(apps, _):
    Mail = apps.get_model("settool_common", "Mail")
    TutorMail = apps.get_model("tutors", "TutorMail")
    for mail in Mail.objects.filter(sender=settool_common.models.Mail.SET_TUTOR):
        TutorMail.objects.create(
            pk=mail.pk,
            sender=settool_common.models.Mail.SET_TUTOR,
            subject=mail.subject,
            text=mail.text,
            comment=mail.comment,
        )
        mail.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
        ("tutors", "0003_auto_20181005_1855"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorMail",
            fields=[
                (
                    "mail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="settool_common.mail",
                    ),
                ),
            ],
            bases=("settool_common.mail",),
        ),
        migrations.RunPython(migrate_mail_tutormail),
    ]
