# Generated by Django 3.1.5 on 2021-01-30 20:03

import django.db.models.deletion
from django.db import migrations
from django.db import models

import settool_common.models as common_models


def migrate_mail_tutormail(apps, _):
    Mail = apps.get_model("settool_common", "Mail")
    TutorMail = apps.get_model("tutors", "TutorMail")
    for mail in Mail.objects.filter(sender=common_models.Mail.SET_TUTOR):
        TutorMail.objects.create(
            pk=mail.pk,
            sender=common_models.Mail.SET_TUTOR,
            subject=mail.subject,
            text=mail.text,
            comment=mail.comment,
        )
        mail.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
        ("tutors", "0003_auto_20181005_1855"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorMail",
            fields=[
                (
                    "mail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="settool_common.mail",
                    ),
                ),
            ],
            bases=("settool_common.mail",),
        ),
        migrations.RunPython(migrate_mail_tutormail),
        migrations.AlterField(
            model_name="mailtutortask",
            name="mail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tutors.tutormail",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="mail_confirmed_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors_mail_confirmed_place",
                to="tutors.tutormail",
                verbose_name="Mail Confirmed Place",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="mail_declined_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors_mail_declined_place",
                to="tutors.tutormail",
                verbose_name="Mail Declined Place",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="mail_registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors_mail_registration",
                to="tutors.tutormail",
                verbose_name="Mail Registration",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="mail_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors_mail_task",
                to="tutors.tutormail",
                verbose_name="Mail Task",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="mail_waiting_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors_mail_waiting_list",
                to="tutors.tutormail",
                verbose_name="Mail Waiting List",
            ),
        ),
    ]
