# Generated by Django 3.2.5 on 2021-07-27 19:34

import django.db.models.deletion
from django.db import migrations, models

import tutors.models


def migrate_locations(apps, _):
    Task = apps.get_model("tutors", "task")
    Event = apps.get_model("tutors", "event")
    Location = apps.get_model("tutors", "Location")

    # get all tuples of (id,en,de)
    locations = set()
    for task in Task.objects.all():
        l_tuple = (task.meeting_point or "", task.meeting_point_en or "", task.meeting_point_de or "")
        locations.add(l_tuple)
    for event in Event.objects.all():
        l_tuple = (event.meeting_point or "", event.meeting_point_en or "", event.meeting_point_de or "")
        locations.add(l_tuple)

    # convert tuples to Locations
    l_map = {}
    for shortname, shortname_en, shortname_de in locations:
        location = Location.objects.create(
            shortname=shortname,
            shortname_en=shortname_en,
            shortname_de=shortname_de,
        )
        l_map[(shortname, shortname_en, shortname_de)] = location

    # save new Locations to the DateGroups
    for task in Task.objects.all():
        l_tuple = (task.meeting_point or "", task.meeting_point_en or "", task.meeting_point_de or "")
        task.associated_meetings.location = l_map[l_tuple]
        task.associated_meetings.save()
    for event in Event.objects.all():
        l_tuple = (event.meeting_point or "", event.meeting_point_en or "", event.meeting_point_de or "")
        event.associated_meetings.location = l_map[l_tuple]
        event.associated_meetings.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0006_auto_20210216_0111"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shortname", models.CharField(max_length=100, verbose_name="short/simplified Address")),
                ("shortname_de", models.CharField(max_length=100, null=True, verbose_name="short/simplified Address")),
                ("shortname_en", models.CharField(max_length=100, null=True, verbose_name="short/simplified Address")),
                ("address", models.CharField(blank=True, max_length=100, verbose_name="(Street)map-address")),
                (
                    "address_de",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="(Street)map-address"),
                ),
                (
                    "address_en",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="(Street)map-address"),
                ),
                ("room", models.CharField(blank=True, max_length=50, verbose_name="Room")),
                ("comment", models.CharField(blank=True, max_length=200, verbose_name="Comment")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="event_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_event_event_leader",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_event_meeting_chairperson",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="meeting_chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_task_meeting_chairperson",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_task_task_leader",
                to="tutors.tutor",
            ),
        ),
        migrations.CreateModel(
            name="DateGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.CharField(blank=True, max_length=200, verbose_name="Comment")),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tutors.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(verbose_name="Date and Time")),
                ("probable_length", models.IntegerField(default=60, verbose_name="probable length in minutes")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.dategroup")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="associated_meetings",
            field=models.ForeignKey(
                default=tutors.models.create_new_date_group,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tutors.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="associated_meetings",
            field=models.ForeignKey(
                default=tutors.models.create_new_date_group,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tutors.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.RunPython(migrate_locations),
        migrations.RemoveField(
            model_name="event",
            name="meeting_point",
        ),
        migrations.RemoveField(
            model_name="event",
            name="meeting_point_de",
        ),
        migrations.RemoveField(
            model_name="event",
            name="meeting_point_en",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_point",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_point_de",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_point_en",
        ),
    ]
