# Generated by Django 3.2.8 on 2021-11-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0006_auto_20210216_0111"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="mail_reminder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_mail_reminder",
                to="tutors.tutormail",
                verbose_name="Mail Reminder",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="reminder_tour_days_count",
            field=models.IntegerField(
                default=0,
                verbose_name="Send the reminder-mail automatically this amount of days before the beginn of the Task "
                "(0=same day)",
            ),
        ),
    ]
