# Generated by Django 3.2.5 on 2021-07-30 18:55

import django.db.models.deletion
from django.db import migrations, models

import kalendar.models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendar", "0001_initial"),
        ("tutors", "0006_auto_20210216_0111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="meeting_point",
        ),
        migrations.RemoveField(
            model_name="event",
            name="meeting_point_de",
        ),
        migrations.RemoveField(
            model_name="event",
            name="meeting_point_en",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_point",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_point_de",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_point_en",
        ),
        migrations.AddField(
            model_name="event",
            name="associated_meetings",
            field=models.ForeignKey(
                default=kalendar.models.DateGroup.create_new_date_group,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_event_event_leader",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_event_meeting_chairperson",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="associated_meetings",
            field=models.ForeignKey(
                default=kalendar.models.DateGroup.create_new_date_group,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="meeting_chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_task_meeting_chairperson",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_task_task_leader",
                to="tutors.tutor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tutors",
            field=models.ManyToManyField(
                blank=True,
                related_name="tutors_task_tutors",
                through="tutors.TutorAssignment",
                to="tutors.Tutor",
                verbose_name="Assigned tutors",
            ),
        ),
        migrations.CreateModel(
            name="TaskSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.task")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.event")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_subscribers",
            field=models.ManyToManyField(
                blank=True,
                through="tutors.EventSubscriber",
                to="tutors.Tutor",
                verbose_name="Subscribers to all meetings",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="meeting_subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="tutors_task_meeting_subscribers",
                through="tutors.TaskSubscriber",
                to="tutors.Tutor",
                verbose_name="Subscribers to all meetings",
            ),
        ),
    ]
