# Generated by Django 3.2.5 on 2021-07-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0007_auto_20210730_2055"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasksubscriber",
            name="task",
        ),
        migrations.RemoveField(
            model_name="tasksubscriber",
            name="tutor",
        ),
        migrations.RemoveField(
            model_name="event",
            name="meeting_subscribers",
        ),
        migrations.RemoveField(
            model_name="task",
            name="meeting_subscribers",
        ),
        migrations.DeleteModel(
            name="EventSubscriber",
        ),
        migrations.DeleteModel(
            name="TaskSubscriber",
        ),
    ]
