# Generated by Django 3.2.5 on 2021-07-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0007_auto_20210727_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tutors",
            field=models.ManyToManyField(
                blank=True,
                related_name="tutors_task_tutors",
                through="tutors.TutorAssignment",
                to="tutors.Tutor",
                verbose_name="Assigned tutors",
            ),
        ),
        migrations.CreateModel(
            name="TaskSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.task")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.event")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DateSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.date")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="date",
            name="meeting_subscribers",
            field=models.ManyToManyField(
                blank=True,
                through="tutors.DateSubscriber",
                to="tutors.Tutor",
                verbose_name="Subscribers to one meeting",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_subscribers",
            field=models.ManyToManyField(
                blank=True,
                through="tutors.EventSubscriber",
                to="tutors.Tutor",
                verbose_name="Subscribers to all meetings",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="meeting_subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="tutors_task_meeting_subscribers",
                through="tutors.TaskSubscriber",
                to="tutors.Tutor",
                verbose_name="Subscribers to all meetings",
            ),
        ),
    ]
