# Generated by Django 4.0.3 on 2022-03-23 00:34

import django.db.models.deletion
from django.db import migrations, models


def initialise_associated_meetings(apps, _):
    DateGroup = apps.get_model("kalendar", "dategroup")

    Task = apps.get_model("tutors", "task")
    Event = apps.get_model("tutors", "event")
    for instance in list(Event.objects.all()) + list(Task.objects.all()):
        date_group = instance.associated_meetings
        if not date_group:
            date_group = DateGroup.objects.create()
            instance.associated_meetings = date_group
            instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("kalendar", "0001_initial"),
        ("tutors", "0008_auto_20220321_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="associated_meetings",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="associated_meetings",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.RunPython(initialise_associated_meetings),
        migrations.AddField(
            model_name="event",
            name="event_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_event_event_leader",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_event_meeting_chairperson",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="meeting_chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_task_meeting_chairperson",
                to="tutors.tutor",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors_task_task_leader",
                to="tutors.tutor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name_de",
            field=models.CharField(max_length=250, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name_en",
            field=models.CharField(max_length=250, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="tutors",
            field=models.ManyToManyField(
                blank=True,
                related_name="tutors_task_tutors",
                through="tutors.TutorAssignment",
                to="tutors.tutor",
                verbose_name="Assigned tutors",
            ),
        ),
    ]
