# Generated by Django 3.2.5 on 2021-07-30 21:17

import django.db.models.deletion
from django.db import migrations, models

import kalendar.models


class Migration(migrations.Migration):

    dependencies = [
        ("kalendar", "0002_dategroupsubscriber"),
        ("tutors", "0008_auto_20210730_2305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="associated_meetings",
            field=models.OneToOneField(
                default=kalendar.models.DateGroup.create_new_date_group,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="associated_meetings",
            field=models.OneToOneField(
                default=kalendar.models.DateGroup.create_new_date_group,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
    ]
