# Generated by Django 3.2.5 on 2021-08-12 08:50

from math import ceil

from django.db import migrations, models


def migrate_start_end_to_dategroup(apps, _):
    Date = apps.get_model("kalendar", "date")
    Task = apps.get_model("tutors", "task")
    for task in Task.objects.all():
        start = task.begin
        end = task.end
        time_length = ceil((end - start).seconds / 60)
        date_group = task.associated_meetings
        Date.objects.create(group=date_group, date=start, probable_length=time_length)

    Event = apps.get_model("tutors", "event")
    for event in Event.objects.all():
        start = event.begin
        end = event.end
        time_length = ceil((end - start).seconds / 60)
        date_group = event.associated_meetings
        Date.objects.create(group=date_group, date=start, probable_length=time_length)


class Migration(migrations.Migration):
    dependencies = [
        ("kalendar", "0003_dategroup_subscribers"),
        ("tutors", "0009_auto_20210730_2317"),
    ]

    operations = [
        migrations.RunPython(migrate_start_end_to_dategroup),
        migrations.RemoveField(
            model_name="event",
            name="begin",
        ),
        migrations.RemoveField(
            model_name="event",
            name="end",
        ),
        migrations.RemoveField(
            model_name="task",
            name="begin",
        ),
        migrations.RemoveField(
            model_name="task",
            name="end",
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name_de",
            field=models.CharField(max_length=250, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name_en",
            field=models.CharField(max_length=250, null=True, verbose_name="Name"),
        ),
    ]
