# Generated by Django 4.0.3 on 2022-04-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0018_alter_anonymisationlog_semester"),
        ("tutors", "0009_alter_event_id_alter_event_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AlterField(
            model_name="subjecttutorcountassignment",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.semester",
                verbose_name="Semester",
            ),
        ),
    ]
