# Generated by Django 4.0.3 on 2022-03-24 15:33

from django.db import migrations


def migrate_meeting_point_to_locaton(apps, _):
    Location = apps.get_model("kalendar", "Location")

    locations: dict[tuple[str, str, str], Location] = {}

    Task = apps.get_model("tutors", "task")
    Event = apps.get_model("tutors", "event")
    for instance in list(Event.objects.all()) + list(Task.objects.all()):
        mp_trans = instance.meeting_point, instance.meeting_point_de, instance.meeting_point_en
        date_group = instance.associated_meetings
        if mp_trans not in locations:
            (meeting_point, meeting_point_de, meeting_point_en) = mp_trans
            location = Location.objects.create(
                shortname=meeting_point,
                shortname_de=meeting_point_de,
                shortname_en=meeting_point_en,
            )
            locations[mp_trans] = location
        date_group.location = locations[mp_trans]
        date_group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("kalendar", "0001_initial"),
        ("tutors", "0010_migrate_start_end_to_dategroup"),
    ]

    operations = [
        migrations.RunPython(migrate_meeting_point_to_locaton),
        migrations.RemoveField(model_name="event", name="meeting_point"),
        migrations.RemoveField(model_name="event", name="meeting_point_de"),
        migrations.RemoveField(model_name="event", name="meeting_point_en"),
        migrations.RemoveField(model_name="task", name="meeting_point"),
        migrations.RemoveField(model_name="task", name="meeting_point_de"),
        migrations.RemoveField(model_name="task", name="meeting_point_en"),
    ]
