# Generated by Django 4.0.6 on 2022-09-01 21:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0010_alter_event_semester_alter_question_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
