BBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
        XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXXXXXXX

        XXXXXXX gettext('SET')  BBBBB BBBBBBBBBBBBBXXXXXXXX
    XXXXXXX

    XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXX


                
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
                        
                         #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

                    XXXXX

                    
                     #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #
 #

                    
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            
            BB BBBBBBBB
                BBBBBBBBBBBBBBBBBB BBBBBBBB
            BBBBB

            
            BBBBB BBBBBBBBBBBBBBB
        XXXXXX

        XXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXX
                    XXXX
                XXXX
            XXXXXX
        XXXXXXXXX
    XXXXXXX
XXXXXXX

