# Generated by Django 4.0.3 on 2022-03-23 00:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tutors", "0008_auto_20220321_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("date", models.DateTimeField(verbose_name="Date and Time")),
                ("probable_length", models.IntegerField(default=60, verbose_name="probable length in minutes")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DateGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("comment", models.CharField(blank=True, default="", max_length=200, verbose_name="Comment")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("shortname", models.CharField(max_length=200, verbose_name="short/simplified Address")),
                ("shortname_de", models.CharField(max_length=200, null=True, verbose_name="short/simplified Address")),
                ("shortname_en", models.CharField(max_length=200, null=True, verbose_name="short/simplified Address")),
                ("address", models.CharField(blank=True, max_length=100, verbose_name="(Street)map-address")),
                (
                    "address_de",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="(Street)map-address"),
                ),
                (
                    "address_en",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="(Street)map-address"),
                ),
                ("room", models.CharField(blank=True, max_length=50, verbose_name="Room")),
                ("comment", models.CharField(blank=True, max_length=200, verbose_name="Comment")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DateSubscriber",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("date", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kalendar.date")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DateGroupSubscriber",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("date", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kalendar.dategroup")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dategroup",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendar.location",
            ),
        ),
        migrations.AddField(
            model_name="dategroup",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                through="kalendar.DateGroupSubscriber",
                to="tutors.tutor",
                verbose_name="Subscribers to a date_group",
            ),
        ),
        migrations.AddField(
            model_name="date",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kalendar.dategroup"),
        ),
        migrations.AddField(
            model_name="date",
            name="meeting_subscribers",
            field=models.ManyToManyField(
                blank=True,
                through="kalendar.DateSubscriber",
                to="tutors.tutor",
                verbose_name="Subscribers to one meeting",
            ),
        ),
    ]
