# Generated by Django 3.2.5 on 2021-07-30 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0008_auto_20210730_2305"),
        ("kalendar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateGroupSubscriber",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="kalendar.dategroup")),
                ("tutor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tutors.tutor")),
            ],
        ),
    ]
