# Generated by Django 3.2.5 on 2021-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutors", "0009_auto_20210730_2317"),
        ("kalendar", "0002_dategroupsubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="dategroup",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                through="kalendar.DateGroupSubscriber",
                to="tutors.Tutor",
                verbose_name="Subscribers to a date_group",
            ),
        ),
    ]
