# Generated by Django 1.9 on 2016-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='car_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Places in my car'),
        ),
        migrations.AlterField(
            model_name='person',
            name='non_liability',
            field=models.DateField(blank=True, verbose_name='Non-liability submitted'),
        ),
        migrations.AlterField(
            model_name='person',
            name='paid',
            field=models.DateField(blank=True, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='person',
            name='payment_deadline',
            field=models.DateField(blank=True, verbose_name='Payment deadline'),
        ),
    ]
