# Generated by Django 1.9 on 2016-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0002_auto_20160906_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="non_liability",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Non-liability submitted",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="paid",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Paid",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="payment_deadline",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Payment deadline",
            ),
        ),
    ]
