# Generated by Django 1.9 on 2016-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0003_auto_20160906_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.CharField(blank=True, max_length=400, verbose_name='Comment'),
        ),
    ]
