# Generated by Django 1.9 on 2016-09-09 19:20

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0004_auto_20151220_2255"),
        ("fahrt", "0009_participant_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fahrt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        verbose_name="Date",
                    ),
                ),
                (
                    "semester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settool_common.Semester",
                    ),
                ),
            ],
        ),
    ]
