# Generated by Django 1.9 on 2016-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fahrt", "0011_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="text",
            field=models.TextField(
                help_text="You may use {{vorname}} for the participant's first name.",
                verbose_name="Text",
            ),
        ),
    ]
