# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0013_auto_20160917_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fahrt_mail_set', to='settool_common.Semester'),
        ),
    ]
