# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0016_auto_20160918_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrt',
            name='close_registration',
            field=models.DateTimeField(verbose_name='Close registration'),
        ),
        migrations.AlterField(
            model_name='fahrt',
            name='open_registration',
            field=models.DateTimeField(verbose_name='Open registration'),
        ),
    ]
