# Generated by Django 1.9 on 2016-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0017_auto_20160918_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="text",
            field=models.TextField(
                help_text=(
                    "You may use {{vorname}} for the participant's first name and {{frist}} for "
                    "the individual payment deadline."
                ),
                verbose_name="Text",
            ),
        ),
    ]
