# Generated by Django 1.9 on 2016-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0018_auto_20160924_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='car_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of people I can take along additionally'),
        ),
    ]
