# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0019_auto_20161001_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('confirmed', 'confirmed'), ('waitinglist', 'waitinglist'), ('cancelled', 'cancelled')], default='registered', max_length=200, verbose_name='Status'),
        ),
    ]
