# Generated by Django 2.0.4 on 2018-07-04 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahrt', '0020_auto_20161005_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fahrt',
            name='semester',
            field=models.OneToOneField(on_delete=None, to='settool_common.Semester'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='participant',
            field=models.ForeignKey(on_delete=None, to='fahrt.Participant'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='mylogentry_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='semester',
            field=models.ForeignKey(on_delete=None, related_name='fahrt_mail_set', to='settool_common.Semester'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='semester',
            field=models.ForeignKey(on_delete=None, related_name='fahrt_participant', to='settool_common.Semester'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='subject',
            field=models.ForeignKey(on_delete=None, related_name='fahrt_participant', to='settool_common.Subject', verbose_name='Subject'),
        ),
    ]
