# Generated by Django 2.0.4 on 2018-10-05 19:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0022_auto_20181005_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("diverse", "diverse"),
                ],
                max_length=200,
                verbose_name="Gender",
            ),
        ),
    ]
