# Generated by Django 3.1.6 on 2021-02-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0025_auto_20210130_2103"),
    ]

    operations = [
        migrations.AddField(
            model_name="fahrt",
            name="mail_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fahrt_mail_registration",
                to="fahrt.fahrtmail",
                verbose_name="Mail Registration",
            ),
        ),
    ]
