# Generated by Django 3.1.6 on 2021-02-16 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fahrt", "0026_fahrt_mail_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="fahrt",
            name="mail_payment_deadline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fahrt_mail_payment_deadline",
                to="fahrt.fahrtmail",
                verbose_name="Mail Payment-Deadline Reminder",
            ),
        ),
        migrations.AddField(
            model_name="fahrt",
            name="mail_reminder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fahrt_mail_reminder",
                to="fahrt.fahrtmail",
                verbose_name="Mail Reminder",
            ),
        ),
        migrations.AddField(
            model_name="fahrt",
            name="reminder_payment_deadline_days_count",
            field=models.IntegerField(
                default=0,
                verbose_name="Send the Payment-Deadline Reminder-mail automatically this amount of days before the "
                "Deadline (0=same day)",
            ),
        ),
        migrations.AddField(
            model_name="fahrt",
            name="reminder_tour_days_count",
            field=models.IntegerField(
                default=0,
                verbose_name="Send the Reminder-mail automatically this amount of days before the Fahrt (0=same day)",
            ),
        ),
        migrations.AlterField(
            model_name="fahrt",
            name="mail_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fahrt_mail_registration",
                to="fahrt.fahrtmail",
                verbose_name="Mail Registration",
            ),
        ),
    ]
