# Generated by Django 3.1.6 on 2021-02-20 23:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


def gen_uuid(apps, _):
    Participant = apps.get_model("fahrt", "participant")
    for row in Participant.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("fahrt", "0028_auto_20210218_2258"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="publish_contact_to_other_paricipants",
            field=models.BooleanField(
                default=False,
                verbose_name="Publish your most relevant (mobile > phone > "
                "email), contact-info to other Fahrt-participants.",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="participant",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="transportation",
            name="deparure_place",
            field=models.CharField(blank=True, max_length=100, verbose_name="The place we will start our trip"),
        ),
        migrations.AddField(
            model_name="transportation",
            name="deparure_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Planned time of departure for the trip (" "leave blank if you dont have a " "preferance)",
            ),
        ),
        migrations.AddField(
            model_name="transportation",
            name="return_departure_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Planned time of departure for the return-trip "
                "(leave blank if you dont have a preferance)",
            ),
        ),
        migrations.AlterField(
            model_name="transportation",
            name="fahrt",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fahrt.fahrt"),
        ),
    ]
