# Generated by Django 4.0.3 on 2022-03-21 18:11

from django.db import migrations

def migrate_mail_fahrtmail(apps, _):
    Mail = apps.get_model("settool_common", "Mail")
    FahrtMail = apps.get_model("fahrt", "FahrtMail")
    for mail in Mail.objects.filter(sender=Mail.SET_FAHRT):
        FahrtMail.objects.create(
            sender=Mail.SET_FAHRT,
            subject=mail.subject,
            text=mail.text,
            comment=mail.comment,
        )
        mail.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('settool_common', "0016_alter_coursebundle_options_alter_subject_options_and_more"),
        ('fahrt', '0029_auto_20210221_0017'),
    ]

    operations = [
        migrations.RunPython(migrate_mail_fahrtmail),
    ]
