# Generated by Django 4.0.3 on 2022-04-01 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fahrt", "0030_auto_20220321_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="fahrt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name="fahrt", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AddField(
            model_name="logentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name="logentry", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AddField(
            model_name="participant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name="participant", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AddField(
            model_name="transportation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(model_name="transportation", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.AddField(
            model_name="transportationcomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transportationcomment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
