# Generated by Django 4.0.3 on 2022-04-01 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fahrt", "0031_rename_deparure_place_transportation_departure_place_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="transportation", old_name="deparure_place", new_name="departure_place"),
    ]
