# Generated by Django 4.0.3 on 2022-04-04 19:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_participant_id_for_log_entry(apps, _):
    LogEntry = apps.get_model("fahrt", "LogEntry")
    for row in LogEntry.objects.all():
        row.participant_uuid_id = row.participant.uuid
        row.save(update_fields=["participant_uuid"])


def migrate_participant_id_for_transportation_comment(apps, _):
    TransportationComment = apps.get_model("fahrt", "TransportationComment")
    for row in TransportationComment.objects.all():
        row.sender_uuid_id = row.sender.uuid
        row.save(update_fields=["sender_uuid"])


def migrate_participant_id_for_transportation(apps, _):
    Transportation = apps.get_model("fahrt", "Transportation")
    for row in Transportation.objects.all():
        row.creator_uuid_id = row.creator.uuid
        row.save(update_fields=["creator_uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("fahrt", "0032_rename_deparure_place_transportation_departure_place_and_more"),
    ]
    operations = [
        migrations.AlterField(
            model_name="participant",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, unique=True),
        ),
        # following https://stackoverflow.com/a/48235821
        # add different fk-fields for each participant and logentry
        migrations.AddField(
            model_name="logentry",
            name="participant_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logentry_uuid",
                to="fahrt.participant",
                to_field="uuid",
                db_constraint=False,
            ),
        ),
        migrations.AddField(
            model_name="transportationcomment",
            name="sender_uuid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportationcomment_uuid",
                to="fahrt.participant",
                to_field="uuid",
                db_constraint=False,
            ),
        ),
        migrations.AddField(
            model_name="transportation",
            name="creator_uuid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fahrt_transportation_creator_uuid",
                to="fahrt.participant",
                to_field="uuid",
                db_constraint=False,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logentry",
                to="fahrt.participant",
            ),
        ),
        migrations.AlterField(
            model_name="transportationcomment",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transportationcomment",
                to="fahrt.participant",
            ),
        ),
        # fill new fields with valid data
        migrations.RunPython(migrate_participant_id_for_transportation_comment),
        migrations.RunPython(migrate_participant_id_for_transportation),
        migrations.RunPython(migrate_participant_id_for_log_entry),
        # after filling, we can assure the db, that they are filled
        migrations.AlterField(
            model_name="logentry",
            name="participant_uuid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logentry_uuid",
                to="fahrt.participant",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transportationcomment",
            name="sender_uuid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logentry_uuid",
                to="fahrt.participant",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transportation",
            name="creator_uuid",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fahrt_transportation_creator_uuid",
                to="fahrt.participant",
                to_field="uuid",
            ),
        ),
        # remove old fields and rename new ones
        migrations.RemoveField(model_name="logentry", name="participant"),
        migrations.RenameField(model_name="logentry", old_name="participant_uuid", new_name="participant"),
        migrations.RemoveField(model_name="transportationcomment", name="sender"),
        migrations.RenameField(model_name="transportationcomment", old_name="sender_uuid", new_name="sender"),
        migrations.RemoveField(model_name="transportation", name="creator"),
        migrations.RenameField(model_name="transportation", old_name="creator_uuid", new_name="creator"),
    ]
