# Generated by Django 4.0.3 on 2022-04-04 19:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0033_logentry_participant_uuid_and_more"),
    ]

    operations = [
        # uuid->id
        migrations.RemoveField(model_name="participant", name="id"),
        migrations.AlterField(
            model_name="participant",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RenameField(
            model_name="participant",
            old_name="uuid",
            new_name="id",
        ),
        # cleanup
        migrations.AlterField(
            model_name="transportationcomment",
            name="sender",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fahrt.participant"),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="participant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="fahrt.participant"),
        ),
        migrations.AlterField(
            model_name="transportation",
            name="creator",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fahrt_transportation_creator",
                to="fahrt.participant",
            ),
        ),
    ]
