# Generated by Django 4.0.3 on 2022-04-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0035_alter_participant_semester"),
    ]

    operations = [
        migrations.RemoveField(model_name="logentry", name="time"),
    ]
