# Generated by Django 4.0.6 on 2022-09-01 21:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fahrt", "0035_alter_participant_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
