# Generated by Django 1.9 on 2015-12-20 15:26

from typing import List
from typing import Tuple

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("WS", "Winter semester"),
                            ("SS", "Summer semester"),
                        ],
                        default="WS",
                        max_length=2,
                        verbose_name="Semester",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        verbose_name="Year",
                    ),
                ),
            ],
        ),
    ]
