# Generated by Django 1.9 on 2015-12-20 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("semester", "year")},
        ),
    ]
