# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settool_common', '0002_auto_20151220_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', 'semester']},
        ),
    ]
