# Generated by Django 1.9 on 2015-12-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0003_auto_20151220_1633"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            (b"BA", "Bachelor"),
                            (b"MA", "Master"),
                        ],
                        default=b"BA",
                        max_length=2,
                        verbose_name="Degree",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            (b"Mathe", "Mathematics"),
                            (b"Physik", "Physics"),
                            (b"Info", "Informatics"),
                            (b"Games", "Informatics: Games Engineering"),
                            (b"Winfo", "Information Systems"),
                            (b"ASE", "Automotive Software Engineering"),
                            (b"CSE", "Computational Science and Engineering"),
                            (b"BMC", "Biomedical Computing"),
                            (b"Robotics", "Robotics, Cognition, Intelligence"),
                            (b"Mathe OR", "Mathematics in Operatios Research"),
                            (b"Mathe SE", "Mathematics in Science and Engineering"),
                            (b"Mathe Finance", "Mathematics in Finance and Acturial Science"),
                            (b"Mathe Bio", "Mathematics in Bioscience"),
                        ],
                        default=b"Info",
                        max_length=20,
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "ordering": ["degree", "subject"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("degree", "subject")},
        ),
    ]
