# Generated by Django 3.1.5 on 2021-01-20 18:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0008_auto_20181005_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="sender",
            field=models.CharField(
                choices=[
                    ("SET-Team <set@fs.tum.de>", "SET"),
                    ("SET-Fahrt-Team <setfahrt@fs.tum.de>", "SET_FAHRT"),
                    ("SET-Tutor-Team <set-tutoren@fs.tum.de>", "SET_TUTOR"),
                    ("Sponsoring-Team des SET-Referats <set-tueten@fs.tum.de>", "SET_BAGS"),
                ],
                default="SET-Team <set@fs.tum.de>",
                max_length=100,
                verbose_name="From",
            ),
        ),
    ]
