# Generated by Django 3.1.5 on 2021-01-22 17:50

from django.db import migrations
from django.db import models


def comment_defaults_to_blank(apps, _):
    Mail = apps.get_model("settool_common", "mail")
    for mail in Mail.objects.all():
        mail.comment = ""
        mail.save()


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0009_auto_20210120_1903"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Comment"),
        ),
        migrations.RunPython(comment_defaults_to_blank),
    ]
