# Generated by Django 3.1.7 on 2021-03-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=200)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes")),
            ],
        ),
    ]
