# Generated by Django 3.1.7 on 2021-03-15 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0012_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymisationLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anon_log_str", models.CharField(max_length=10)),
                (
                    "semester",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="settool_common.semester"),
                ),
            ],
        ),
    ]
