# Generated by Django 3.1.7 on 2021-03-19 19:55

import django.db.models.deletion
from django.db import migrations, models


def course_bundle_creation(apps, _):
    CourseBundle = apps.get_model("settool_common", "CourseBundle")
    Subject = apps.get_model("settool_common", "subject")

    previous_translations = {
        "Mathe": ("Mathematics", "Mathematik"),
        "Physik": ("Physics", "Physik"),
        "Info": ("Informatics", "Informatik"),
        "Games": ("Informatics: Games Engineering", "Informatik: Games Engineering"),
        "Winfo": ("Information Systems", "Wirtschaftsinformatik"),
        "ASE": ("Automotive Software Engineering", "Automotive Software Engineering"),
        "CSE": ("Computational Science and Engineering", "Computational Science and Engineering"),
        "BMC": ("Biomedical Computing", "Biomedical Computing"),
        "Robotics": ("Robotics, Cognition, Intelligence", "Robotics, Cognition, Intelligence"),
        "Mathe OR": ("Mathematics in Operatios Research", "Mathematics in Operatios Research"),
        "Mathe SE": ("Mathematics in Science and Engineering", "Mathematics in Science and Engineering"),
        "Mathe Finance": ("Mathematics in Finance and Acturial Science", "Mathematics in Finance and Acturial Science"),
        "Mathe Bio": ("Mathematics in Bioscience", "Mathematics in Bioscience"),
    }

    if not CourseBundle.objects.exists():
        tmp_c_b = CourseBundle.objects.create(name_en="n.A.", name_de="n.A.")
        for subject in Subject.objects.all():
            subject.course_bundle = tmp_c_b
            sub_transl = previous_translations.get(subject.subject, default=("n.A.", "n.A."))
            subject.subject_de = sub_transl[0]
            subject.subject_en = sub_transl[1]
            subject.save()


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0014_auto_20210317_1107"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseBundle",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=10, verbose_name="Course-bundles' name")),
                ("name_de", models.CharField(max_length=10, null=True, verbose_name="Course-bundles' name")),
                ("name_en", models.CharField(max_length=10, null=True, verbose_name="Course-bundles' name")),
            ],
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_de",
            field=models.CharField(max_length=20, null=True, verbose_name="Subject"),
        ),
        migrations.AddField(
            model_name="subject",
            name="subject_en",
            field=models.CharField(max_length=20, null=True, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject",
            field=models.CharField(max_length=20, verbose_name="Subject"),
        ),
        migrations.AddField(
            model_name="subject",
            name="course_bundle",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.coursebundle",
                verbose_name="Course-bundle",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(course_bundle_creation),
    ]
