# Generated by Django 4.0.1 on 2022-02-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settool_common", "0015_auto_20210319_2055"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursebundle",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["degree", "course_bundle", "subject"]},
        ),
        migrations.AlterField(
            model_name="coursebundle",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Course-bundles' name"),
        ),
        migrations.AlterField(
            model_name="coursebundle",
            name="name_de",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Course-bundles' name"),
        ),
        migrations.AlterField(
            model_name="coursebundle",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name="Course-bundles' name"),
        ),
    ]
