# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settool_common', '0003_auto_20151220_1633'),
        ('guidedtours', '0002_participant_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settool_common.Semester'),
            preserve_default=False,
        ),
    ]
