# Generated by Django 1.9 on 2015-12-20 16:20

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0003_auto_20151220_1633"),
        ("guidedtours", "0002_participant_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="semester",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="settool_common.Semester",
            ),
            preserve_default=False,
        ),
    ]
