# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 22:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settool_common', '0004_auto_20151220_2255'),
        ('guidedtours', '0003_tour_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settool_common.Subject'),
            preserve_default=False,
        ),
    ]
