# Generated by Django 1.9 on 2015-12-21 08:08

import datetime

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0004_participant_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="time",
            field=models.DateTimeField(
                default=timezone.now,
                verbose_name="Registration Time",
            ),
        ),
    ]
