# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:08
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedtours', '0004_participant_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Registration Time'),
        ),
    ]
