# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidedtours', '0005_participant_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='capacity',
            field=models.PositiveIntegerField(default=20, verbose_name='Capacity'),
            preserve_default=False,
        ),
    ]
