# Generated by Django 1.9 on 2016-09-21 09:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0008_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="text",
            field=models.TextField(
                help_text=(
                    "You may use {{vorname}} for the participant's first name, {{tour}} for the "
                    "name of the tour, {{zeit}} for the time of the tour."
                ),
                verbose_name="Text",
            ),
        ),
    ]
