# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-24 16:29
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guidedtours', '0009_auto_20160921_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='close_registration',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 16, 29, 14, 841558, tzinfo=utc), verbose_name='Close registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='open_registration',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 16, 29, 20, 865281, tzinfo=utc), verbose_name='Open registration'),
            preserve_default=False,
        ),
    ]
