# Generated by Django 2.0.4 on 2018-07-04 06:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0010_auto_20160924_1829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="semester",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="tours_mail_set",
                to="settool_common.Semester",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="subject",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to="settool_common.Subject",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="tour",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to="guidedtours.Tour",
                verbose_name="Tour",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="semester",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to="settool_common.Semester",
            ),
        ),
    ]
