# Generated by Django 3.1.5 on 2021-01-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0012_auto_20181005_1855"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mail",
            name="semester",
        ),
    ]
