# Generated by Django 3.1.5 on 2021-01-30 20:03

import django.db.models.deletion
from django.db import migrations
from django.db import models

import settool_common.models as common_models


def migrate_mail_tourmail(apps, _):
    Mail = apps.get_model("guidedtours", "Mail")
    TourMail = apps.get_model("guidedtours", "TourMail")
    for mail in Mail.objects.all():
        TourMail.objects.create(
            sender=common_models.Mail.SET,
            subject=mail.subject,
            text=mail.text,
            comment=mail.comment,
        )
        mail.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
        ("guidedtours", "0013_remove_mail_semester"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourMail",
            fields=[
                (
                    "mail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="settool_common.mail",
                    ),
                ),
            ],
            bases=("settool_common.mail",),
        ),
        migrations.RunPython(migrate_mail_tourmail),
        migrations.DeleteModel(
            name="Mail",
        ),
    ]
