# Generated by Django 3.1.6 on 2021-02-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settool_common", "0011_remove_mail_semester"),
        ("guidedtours", "0014_auto_20210130_2103"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mail_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours_mail_registration",
                        to="guidedtours.tourmail",
                        verbose_name="Mail Registration",
                    ),
                ),
                (
                    "semester",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="settool_common.semester"),
                ),
            ],
        ),
    ]
