# Generated by Django 3.1.6 on 2021-02-16 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0015_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="mail_reminder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tours_mail_reminder",
                to="guidedtours.tourmail",
                verbose_name="Mail Reminder",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="reminder_tour_days_count",
            field=models.IntegerField(
                default=0,
                verbose_name="Send the reminder-mail automatically this amount of days before the Tour (0=same day)",
            ),
        ),
    ]
