# Generated by Django 3.1.6 on 2021-02-17 15:25

from django.db import migrations


def rename_duplicates(apps, _):
    Participant = apps.get_model("guidedtours", "participant")
    participant: Participant
    for participant in Participant.objects.all():
        if Participant.objects.filter(tour=participant.tour, email=participant.email).count() > 1:
            participant.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("guidedtours", "0016_auto_20210216_0111"),
    ]

    operations = [
        migrations.RunPython(rename_duplicates),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("tour", "email")},
        ),
    ]
