# Generated by Django 3.1.6 on 2021-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0017_auto_20210217_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="length",
            field=models.IntegerField(
                default=0,
                verbose_name="How long (minutes) a Participant should be blocked after a Tour ("
                "additonal to 30min leadup-blacklist-Time)",
            ),
        ),
    ]
