# Generated by Django 4.0.3 on 2022-04-04 23:04

import django.db.models.deletion
from django.db import migrations, models

import kalendar.models


def migrate_associated_meetings(apps, schema_editor):
    Tour = apps.get_model("guidedtours", "Tour")
    for tour in Tour.objects.all():
        tour.associated_meetings_id = kalendar.models.create_associated_meetings()
        tour.save()


def migrate_tour_dates(apps, schema_editor):
    date_lut = {}
    Date = apps.get_model("kalendar", "Date")
    Tour = apps.get_model("guidedtours", "Tour")
    for tour in Tour.objects.all():
        group = tour.associated_meetings
        date = Date.objects.create(
            group=group,
            date=tour.date,
            probable_length=tour.length,
        )
        date_lut[tour.id] = date

    Participant = apps.get_model("guidedtours", "Participant")
    for participant in Participant.objects.all():
        participant.date = date_lut[participant.tour_id]
        participant.save()


class Migration(migrations.Migration):
    dependencies = [
        ("kalendar", "0002_date_created_at_date_updated_at_dategroup_created_at_and_more"),
        ("guidedtours", "0021_alter_tour_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tour",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="tour",
            name="associated_meetings",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="kalendar.dategroup",
                verbose_name="Associated Meetings",
            ),
        ),
        migrations.RunPython(migrate_associated_meetings),
        migrations.AddField(
            model_name="participant",
            name="date",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="kalendar.date",
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_tour_dates),
        migrations.AlterField(
            model_name="participant",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kalendar.date",
                verbose_name="Date",
            ),
        ),
        migrations.RemoveField(model_name="tour", name="date"),
        migrations.RemoveField(model_name="tour", name="length"),
    ]
