# Generated by Django 4.0.3 on 2022-04-05 15:23

from django.db import migrations


def migrate_participant_time_created_at(apps, schema_editor):
    Participant = apps.get_model("guidedtours", "Participant")
    for participant in Participant.objects.all():
        participant.created_at = participant.time
        participant.save(update_fields=["created_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("kalendar", "0002_date_created_at_date_updated_at_dategroup_created_at_and_more"),
        ("guidedtours", "0022_remove_tour_date_remove_tour_length_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_participant_time_created_at),
        migrations.RemoveField(model_name="participant", name="time"),
    ]
