# Generated by Django 4.0.3 on 2022-04-05 16:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guidedtours", "0024_alter_tour_id"),
    ]

    operations = [
        # uuid->id for original field
        migrations.RemoveField(model_name="tour", name="id"),
        migrations.AlterField(
            model_name="tour",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RenameField(model_name="tour", old_name="uuid", new_name="id"),
        # cleanup
        migrations.AlterField(
            model_name="participant",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="guidedtours.tour",
                verbose_name="Tour",
            ),
        ),
    ]
